# Generated by Django 4.1 on 2023-10-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='api_task',
        ),
    ]
