# Generated by Django 4.1 on 2022-09-18 13:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=201, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='rentals/uploads/')),
                ('image_name', models.CharField(blank=True, max_length=201, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ACCOM_type', models.CharField(choices=[('House', 'Entire House'), ('Apartment', 'Entire Aparment'), ('Room', 'Single Room')], default='Room', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
