# Generated by Django 4.1 on 2022-09-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_review_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='ACCOM_type',
            field=models.CharField(choices=[('Villa', 'Entire Villa'), ('Apartment', 'Entire Aparment'), ('Room', 'Single Room')], default='Room', max_length=20),
        ),
    ]
