# Generated by Django 4.1 on 2024-10-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
