# Generated by Django 4.1 on 2022-10-13 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excurion_name', models.CharField(max_length=201)),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('Full_name', models.CharField(max_length=70)),
                ('image', models.URLField(blank=True, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adult_qty', models.IntegerField()),
                ('child_qty', models.IntegerField()),
                ('excursion_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
