# Generated by Django 4.1 on 2022-10-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='rental_type',
        ),
    ]
