# Generated by Django 4.1 on 2023-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='reference',
            field=models.CharField(default='', max_length=6),
        ),
    ]
