# Generated by Django 4.1 on 2022-10-17 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_excursionorder_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='excursion_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='excursionorder',
            name='image',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
