# Generated by Django 4.1 on 2022-10-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_excursionorder_place_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursionorder',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='excursionorder',
            old_name='Price',
            new_name='price',
        ),
    ]
