# Generated by Django 4.1 on 2022-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_excursionorder_excursion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
