# Generated by Django 4.1 on 2023-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_excursionorder_time_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='infant_qty',
            field=models.IntegerField(default=0),
        ),
    ]
