# Generated by Django 4.1 on 2022-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_full_name_excursionorder_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
