# Generated by Django 4.1 on 2022-10-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_excursionorder_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursionorder',
            old_name='excurion_name',
            new_name='excursion_name',
        ),
    ]
