# Generated by Django 4.1 on 2023-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_excursionorder_infant_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='excursion_date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
