# Generated by Django 4.1 on 2023-09-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_excursionorder_excursion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='excursion_date',
            field=models.DateField(default=''),
        ),
    ]
