# Generated by Django 4.1 on 2022-10-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_excursionorder_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionorder',
            name='order_total',
        ),
    ]
