# Generated by Django 4.1 on 2022-10-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_excursionorder_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
