# Generated by Django 4.1 on 2023-11-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_excursionorder_excursion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='Excursion_data',
            field=models.JSONField(default=dict),
        ),
    ]
