# Generated by Django 4.1 on 2023-12-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_excursionorder_excursion_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='advanced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='excursionorder',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
