# Generated by Django 4.1 on 2023-12-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_excursionorder_advanced_excursionorder_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='where_heard_from_us',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
