# Generated by Django 4.1 on 2023-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_excursionorder_url_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='url_flight',
            field=models.URLField(blank=True, default='', max_length=400, null=True),
        ),
    ]
