# Generated by Django 4.1 on 2023-12-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_excursionorder_url_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='flight_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
