# Generated by Django 4.1 on 2023-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_excursionorder_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='room_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='excursionorder',
            name='send_email_onclick',
            field=models.BooleanField(default=False),
        ),
    ]
