# Generated by Django 4.1 on 2024-01-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_excursionorder_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='cellphone_number',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='excursionorder',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='excursionorder',
            name='place_pickup',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
