# Generated by Django 4.1 on 2024-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_alter_excursionorder_cellphone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='child_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excursionorder',
            name='flight_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='excursionorder',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
