# Generated by Django 4.1 on 2024-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_alter_excursionorder_child_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionorder',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
