# Generated by Django 4.1 on 2024-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_alter_excursionorder_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionorder',
            name='place_dropup',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
