# Generated by Django 4.1 on 2023-11-19 07:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=201, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('post', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
