# Generated by Django 4.1 on 2022-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursions',
            name='images',
        ),
        migrations.AddField(
            model_name='excursions',
            name='image',
            field=models.ImageField(null=True, upload_to='images/excursions/uploads/'),
        ),
    ]
