# Generated by Django 4.1 on 2022-09-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0007_excursions_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursions',
            old_name='alt',
            new_name='image_alt',
        ),
    ]
