# Generated by Django 4.1 on 2022-09-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0008_rename_alt_excursions_image_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionsFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=201, null=True)),
                ('images', models.ImageField(null=True, upload_to='excursions/uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='excursions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursions',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionsfotos'),
        ),
    ]
