# Generated by Django 4.1 on 2022-09-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0009_excursionsfotos_alter_excursions_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursions',
            name='images',
        ),
        migrations.AddField(
            model_name='excursionsfotos',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursions'),
        ),
    ]
