# Generated by Django 4.1 on 2022-09-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0011_rename_excursionsfotos_excursionextraphotos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='excursions/uploads/')),
                ('image_name', models.CharField(blank=True, max_length=201, null=True)),
                ('excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='excursions.excursions')),
            ],
        ),
        migrations.DeleteModel(
            name='ExcursionExtraPhotos',
        ),
    ]
