# Generated by Django 4.1 on 2022-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0014_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
