# Generated by Django 4.1 on 2022-10-19 18:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0015_excursions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
