# Generated by Django 4.1 on 2023-08-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0016_alter_excursions_price_alter_excursions_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='The full name of the account holder.', max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='The name of the bank.', max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='The unique 6-digit reference number.', max_length=6, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, help_text='The bank account number.', max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True, help_text='The date when the reference was created.')),
            ],
        ),
    ]
