# Generated by Django 4.1 on 2023-08-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0017_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='bank_acount_type',
            field=models.CharField(choices=[('CC', 'cuenta corriente '), ('CA', 'Cuenta de ahorro')], default='cuenta corriente ', max_length=20),
        ),
        migrations.AddField(
            model_name='reference',
            name='cedula',
            field=models.CharField(blank=True, help_text='Cedula', max_length=30, null=True),
        ),
    ]
