# Generated by Django 4.1 on 2023-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0018_reference_bank_acount_type_reference_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='due_to_pay_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount that needs to be paid after 3 days.', max_digits=10),
        ),
        migrations.AddField(
            model_name='reference',
            name='has_due_payment',
            field=models.BooleanField(default=False, help_text='Indicates whether there is a due payment or not.'),
        ),
        migrations.AddField(
            model_name='reference',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount of money that has been paid since the account started.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reference',
            name='bank_acount_type',
            field=models.CharField(choices=[('CC', 'Cuenta corriente '), ('CA', 'Cuenta de ahorro')], default='cuenta corriente ', max_length=20),
        ),
    ]
