# Generated by Django 4.1 on 2023-08-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0020_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursions',
            name='status',
        ),
        migrations.AddField(
            model_name='excursions',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
