# Generated by Django 4.1 on 2023-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0021_remove_excursions_status_excursions_is_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
