# Generated by Django 4.1 on 2023-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0022_excursions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the account holder.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number of the account holder.', max_length=20, null=True),
        ),
    ]
