# Generated by Django 4.1 on 2023-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0025_alter_availabletime_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
    ]
