# Generated by Django 4.1 on 2023-09-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0028_dayofweek_excursions_unavailable_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255)),
                ('visit_datetime', models.DateTimeField(auto_now_add=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
