# Generated by Django 4.1 on 2023-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0029_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='duration_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='excursions',
            name='tour_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excursions',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
    ]
