# Generated by Django 4.1 on 2023-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0030_excursions_duration_time_excursions_tour_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='slugy',
            field=models.SlugField(blank=True),
        ),
    ]
