# Generated by Django 4.1 on 2023-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0031_excursions_slugy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='slugy',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
