# Generated by Django 4.1 on 2023-09-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0032_alter_excursions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
