# Generated by Django 4.1 on 2023-09-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0032_alter_excursions_slugy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='System_info',
            field=models.TextField(default='', max_length=600),
        ),
    ]
