# Generated by Django 4.1 on 2023-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0033_pagevisit_system_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
