# Generated by Django 4.1 on 2023-09-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0034_alter_excursions_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursions',
            name='slug',
        ),
    ]
