# Generated by Django 4.1 on 2023-10-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0034_excursions_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
