# Generated by Django 4.1 on 2023-10-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0035_alter_review_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='System_info',
        ),
    ]
