# Generated by Django 4.1 on 2023-10-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0036_remove_pagevisit_system_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'permissions': [('can_add_pagevisit', 'Can add PageVisit'), ('can_change_pagevisit', 'Can change PageVisit'), ('can_delete_pagevisit', 'Can delete PageVisit')]},
        ),
    ]
