# Generated by Django 4.1 on 2023-11-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0037_alter_pagevisit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excurasion_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=201, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='excursions',
            name='company_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='excursions',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='Excurasion_category', to='excursions.excurasion_category'),
        ),
    ]
