# Generated by Django 4.1 on 2023-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0039_excursions_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=201, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='excursions',
            name='type_dropdown',
            field=models.ManyToManyField(blank=True, null=True, related_name='Excursion_type', to='excursions.excursion_type'),
        ),
    ]
