# Generated by Django 4.1 on 2023-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0040_excursion_type_excursions_type_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='dicount',
            field=models.BooleanField(default=True),
        ),
    ]
