# Generated by Django 4.1 on 2023-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0041_excursions_dicount'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='just_adult',
            field=models.BooleanField(default=False),
        ),
    ]
