# Generated by Django 4.1 on 2023-11-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0042_excursions_just_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=201, null=True),
        ),
    ]
