# Generated by Django 4.1 on 2023-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0043_excursions_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='excursions/uploads/'),
        ),
    ]
