# Generated by Django 4.1 on 2023-11-25 07:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0044_alter_excursions_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
