# Generated by Django 4.1 on 2023-11-25 07:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0045_alter_excursions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Default description message'),
        ),
    ]
