# Generated by Django 4.1 on 2023-11-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0047_alter_excursions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='unavailable_days',
            field=models.ManyToManyField(blank=True, null=True, related_name='excursions', to='excursions.dayofweek'),
        ),
    ]
