# Generated by Django 4.1 on 2023-11-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0048_alter_excursions_unavailable_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=201, null=True),
        ),
    ]
