# Generated by Django 4.1 on 2023-12-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0049_alter_excursions_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='price_children',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
