# Generated by Django 4.1 on 2023-12-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0050_excursions_price_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='our_excursions',
            field=models.BooleanField(default=False),
        ),
    ]
