# Generated by Django 4.1 on 2023-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0051_excursions_our_excursions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='Excurasion_category', to='excursions.excurasion_category'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='type_dropdown',
            field=models.ManyToManyField(blank=True, related_name='Excursion_type', to='excursions.excursion_type'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='unavailable_days',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='excursions.dayofweek'),
        ),
    ]
