# Generated by Django 4.1 on 2024-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0053_excursions_reserve_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='reserve_no_pay',
            field=models.BooleanField(default=False),
        ),
    ]
