# Generated by Django 4.1 on 2024-10-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0054_excursions_reserve_no_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursions',
            old_name='Price',
            new_name='price',
        ),
    ]
